---
title: Smarty Pants
---
erDiagram

   UNIVERSITY{
       long id PK
       String name
   }

   UNIVERSITY ||--|{ ACADEMIC_UNIT : ""
   ACADEMIC_UNIT{
       long id PK
       long university_id FK
       String name
   }

   ACADEMIC_UNIT ||--|{ CAREER : ""
   CAREER{
       long id PK
       long academic_unit_id FK
       long career_type_id FK
       String name
   }

   CAREER ||--|| CAREER_TYPE : ""
   CAREER_TYPE{
       long id PK
       String name
   }

   CAREER ||--|{ STUDY_PLAN : ""
   ACADEMIC_UNIT ||--|{ STUDY_PLAN : ""
   STUDY_PLAN{
       long id PK
       long career_id FK
       long academic_unit_id FK
   }

   STUDY_PLAN_ATTRIBUTE{
       long id PK
       String value
   }

   STUDY_PLAN_ATTRIBUTE }|--|{ STUDY_PLAN_ATTRIBUTES : ""
   STUDY_PLAN }|--|{ STUDY_PLAN_ATTRIBUTES : ""
   STUDY_PLAN_ATTRIBUTES{
       long study_plan_id PK, FK
       long study_plan_id_attribute PK, FK
   }

   STUDY_PLAN }|--|{ STUDY_PLAN_VALUE : ""
   STUDY_PLAN }|--|{ STUDY_PLAN_VALUE : ""
   STUDY_PLAN_VALUE{
       long id PK
       long study_plan_id FK
       long study_plan_attibute_id FK
       String value
   }

   REQUIREMENT{
       long id PK
       String value
   }

   STUDY_PLAN }|--|{ STUDY_PLAN_REQUIREMENT : ""
   REQUIREMENT }|--|{ STUDY_PLAN_REQUIREMENT : ""
   STUDY_PLAN_REQUIREMENT{
       long study_plan_id PK, FK
       long requirement_id PK, FK
   }

   REQUIREMENT ||--|{ REQUIREMENT_VALUE : ""
   REQUIREMENT_VALUE{
       long id PK
       long requirement_id FK
       String value
   }

   SUBJECT{
       long id PK
       String name
   }

   SUBJECT }|--|{ SUBJECT_REQUIREMENT : ""
   REQUIREMENT }|--|{ SUBJECT_REQUIREMENT : ""
   SUBJECT_REQUIREMENT{
       long subject_id PK, FK
       long requirement_id PK, FK
   }

   SUBJECT ||--|{ SUBJECT_VALUE : ""
   REQUIREMENT }|--|{ SUBJECT_VALUE : ""
   SUBJECT_VALUE{
       long id PK
       long subject_id FK
       long requirement_id FK
       String value
   }

   SUBJECT }|--|{ SUBJECT_STUDY_PLAN : ""
   STUDY_PLAN }|--|{ SUBJECT_STUDY_PLAN : ""
   SUBJECT_STUDY_PLAN{
       long subject_id PK, FK
       long study_plan_id PK, FK
   }

   SUBJECT ||--|| CORRELATION : ""
   STUDY_PLAN ||--|{ CORRELATION : ""
   SUBJECT ||--|| CORRELATION : ""
   CORRELATION{
       long id PK
       long subject_id FK
       long correlative_subject_id FK
       long study_plan_id FK
   }




