---
title: Smarty Pants
---
erDiagram

   UNIVERSITY{
       long id PK
       String name
   }

   UNIVERSITY ||--|{ ACADEMIC_UNIT : ""
   ACADEMIC_UNIT{
       long id PK
       long university_id FK
       String name
   }

   ACADEMIC_UNIT ||--|{ CAREER : ""
   CAREER{
       long id PK
       long academic_unit_id FK
       long career_type_id FK
       String name
   }

   CAREER }|--|| CAREER_TYPE : ""
   CAREER_TYPE{
       long id PK
       String name
   }

   CAREER ||--|{ STUDY_PLAN : ""
   ACADEMIC_UNIT ||--|{ STUDY_PLAN : ""
   STUDY_PLAN{
       long id PK
       long career_id FK
       long academic_unit_id FK
   }

   STUDY_PLAN_ATTRIBUTE{
       long id PK
       String value
   }

   STUDY_PLAN_ATTRIBUTE }|--|{ STUDY_PLAN_ATTRIBUTES : ""
   STUDY_PLAN }|--|{ STUDY_PLAN_ATTRIBUTES : ""
   STUDY_PLAN_ATTRIBUTES{
       long study_plan_id PK, FK
       long study_plan_id_attribute PK, FK
   }

   STUDY_PLAN }|--|{ STUDY_PLAN_VALUE : ""
   REQUIREMENT }|--|{ STUDY_PLAN_VALUE : ""
   STUDY_PLAN_VALUE{
       long id PK
       long study_plan_id FK
       long requirement_id FK
       String value
   }

   REQUIREMENT{
       long id PK
       String value
   }

   STUDY_PLAN }|--|{ STUDY_PLAN_REQUIREMENT : ""
   REQUIREMENT }|--|{ STUDY_PLAN_REQUIREMENT : ""
   STUDY_PLAN_REQUIREMENT{
       long study_plan_id PK, FK
       long requirement_id PK, FK
   }

    SUBJECT }|--|{ SUBJECT_REQUIREMENT : ""
    REQUIREMENT }|--|{ SUBJECT_REQUIREMENT : ""
    SUBJECT_REQUIREMENT{
        long subject_id PK, FK
        long requirement_id PK, FK
    }

%%   REQUIREMENT ||--|{ REQUIREMENT_VALUE : ""
%%   REQUIREMENT_VALUE{
%%       long id PK
%%       long requirement_id FK
%%       String value
%%   }

   SUBJECT{
       long id PK
       String name
   }

   SUBJECT ||--|{ SUBJECT_VALUE : ""
   REQUIREMENT }|--|{ SUBJECT_VALUE : ""
   SUBJECT_VALUE{
       long id PK
       long subject_id FK
       long requirement_id FK
       String value
   }

   SUBJECT }|--|{ SUBJECT_STUDY_PLAN : ""
   STUDY_PLAN }|--|{ SUBJECT_STUDY_PLAN : ""
   SUBJECT_STUDY_PLAN{
       long subject_id PK, FK
       long study_plan_id PK, FK
   }

   SUBJECT ||--|| CORRELATION : ""
   STUDY_PLAN ||--|{ CORRELATION : ""
   SUBJECT ||--|| CORRELATION : ""
   CORRELATION{
       long id PK
       long subject_id FK
       long correlative_subject_id FK
       long study_plan_id FK
   }

   EXAM{
       long id PK
       long exam_type_id FK
       long dictation_id FK
       String name
       Date date
   }

   EXAM }|--|| EXAM_TYPE : ""
   EXAM_TYPE{
       long id PK
       String name
   }

   EXAM }|--|| DICTATION : ""
   DICTATION{
       long id PK
       int period
       int year
   }

   DICTATION }|--|{ DICTATION_SUBJECT : ""
   SUBJECT }|--|{ DICTATION_SUBJECT : ""
   DICTATION_SUBJECT{
       long dictation_id PK, FK
       long subject_id PK, FK
   }

   USER_ATTRIBUTE{
       long id PK
       String value
   }

   STUDENT{
       long id PK
       long person_id UK
   }

   STUDENT }|--|{ STUDENT_ATTRIBUTE : ""
    USER_ATTRIBUTE }|--|{ STUDENT_ATTRIBUTE : ""
   STUDENT_ATTRIBUTE{
       long student_id PK, FK
       long people_attribute_id PK, FK
   }

   STUDENT_ATTRIBUTE_VALUE }|--|| STUDENT : ""
   STUDENT_ATTRIBUTE_VALUE }|--|| STUDENT_ATTRIBUTE : ""
   STUDENT_ATTRIBUTE_VALUE{
       long id PK
       long student_attribute_id FK
       long student_id FK
       String value
   }

   ASSIGNED_STUDY_PLAN }|--|{ STUDENT : ""
   ASSIGNED_STUDY_PLAN }|--|{ STUDY_PLAN : ""
   ASSIGNED_STUDY_PLAN{
       long student_id PK, FK
       long study_plan_id PK, FK
   }

    TEACHER ||--|| DICTATION : ""
    TEACHER }|--|| TEACHER_TYPE : ""
    TEACHER{
        long id PK
        long person_id UK
        long dictation_id FK
        long teacher_type_id FK
    }

    TEACHER }|--|{ TEACHER_SUBJECT : ""
    SUBJECT }|--|{ TEACHER_SUBJECT : ""
    TEACHER_SUBJECT{
        long teacher_id PK, FK
        long subject_id PK, FK
    }

    TEACHER_TYPE{
        long id PK
        String name
    }

    TEACHER }|--|{ TEACHER_ATTRIBUTE : ""
    USER_ATTRIBUTE }|--|{ TEACHER_ATTRIBUTE : ""
    TEACHER_ATTRIBUTE{
        long teacher_id PK, FK
        long people_attribute_id PK, FK
    }

    TEACHER_ATTRIBUTE_VALUE }|--|| TEACHER : ""
    TEACHER_ATTRIBUTE_VALUE }|--|| TEACHER_ATTRIBUTE : ""
    TEACHER_ATTRIBUTE_VALUE{
        long id PK
        long teacher_attribute_id FK
        long teacher_id FK
        String value
    }

    ADMIN_STAFF ||--|| ACADEMIC_UNIT : ""
    ADMIN_STAFF{
        long id PK
        long person_id UK
        long academic_unit_id FK
    }

    ADMIN_STAFF }|--|{ ADMIN_STAFF_ATTRIBUTE : ""
    USER_ATTRIBUTE }|--|{ ADMIN_STAFF_ATTRIBUTE : ""
    ADMIN_STAFF_ATTRIBUTE{
        long admin_staff_id PK, FK
        long admin_staff_attribute_id PK, FK
    }

    ADMIN_STAFF_ATTRIBUTE_VALUE }|--|| ADMIN_STAFF : ""
    ADMIN_STAFF_ATTRIBUTE_VALUE }|--|| ADMIN_STAFF_ATTRIBUTE : ""
    ADMIN_STAFF_ATTRIBUTE_VALUE{
        long id PK
        long admin_staff_attribute_id FK
        long admin_staff_id FK
        String value
    }

    SCHEDULE ||--|| TIME_SCHEDULE : ""
    SCHEDULE{
        long id PK
        long time_schedule_id FK
        Day day
    }

    TIME_SCHEDULE }|--|| DICTATION : ""
    TIME_SCHEDULE{
        long id PK
        long dictation_id FK
        Date start_time
        Date end_time
    }

%% ver bien lo de los estudiantes que son ayudantes

    CLASSROOM ||--|| SECTOR : ""
    CLASSROOM ||--|| LOCATION : ""
    CLASSROOM{
        long id PK
        long location_id FK
        long sector_id FK
        int capacity
        String name
    }

    CLASSROOM_ATTRIBUTE{
        long id PK
        String value
    }

    CLASSROOM ||--|{ CLASSROOM_ATTRIBUTE_VALUE : ""
    CLASSROOM_ATTRIBUTE ||--|{ CLASSROOM_ATTRIBUTE_VALUE : ""
    CLASSROOM_ATTRIBUTE_VALUE{
        long id PK
        long classroom_id FK
        long classroom_attribute_id FK
        String value
    }

    CLASSROOM }|--|{ CLASSROOM_REQUIREMENT : ""
    CLASSROOM_ATTRIBUTE }|--|{ CLASSROOM_REQUIREMENT : ""
    CLASSROOM_REQUIREMENT{
        long classroom_id PK, FK
        long classroom_attribute_id PK, FK
    }

    UNIVERSITY ||--|{ LOCATION : ""
    LOCATION{
        long id PK
        String street
        int number
        String city
        String state
        String country
    }

    SECTOR{
        long id PK
        String name
    }

    CLASSROOM }|--|{ CLASSROOM_SUBJECT : ""
    SUBJECT }|--|{ CLASSROOM_SUBJECT : ""
    CLASSROOM_SUBJECT{
        long classroom_id PK, FK
        long subject_id PK, FK
    }

    CLASS ||--|| CLASSROOM : ""
    CLASS ||--|{ DICTATION : ""
    CLASS{
        long id PK
        long classroom_id FK
        long dictation_id FK
        int capacity
        String name
    }

    ATTENDANCE{
        long id PK
        long student_id FK
        String value
    }

    ATTENDANCE }|--|{ ATTENDANCE_CLASS : ""
    CLASS }|--|{ ATTENDANCE_CLASS : ""
    ATTENDANCE_CLASS{
        long attendance_id PK, FK
        long class_id PK, FK
    }

    ATTENDANCE }|--|{ ATTENDANCE_EXAM : ""
    EXAM }|--|{ ATTENDANCE_EXAM : ""
    ATTENDANCE_EXAM{
        long attendance_id PK, FK
        long exam_id PK, FK
    }


